name: Deploy

on:
  push:
    branches:
      - main

permissions: 
  contents: write

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm i
      - name: Build
        run: npm run build
      - name: Generate 404.html
        run: cp dist/2023-09-04_2023_m02-ng-top-colleagues/index.html dist/2023-09-04_2023_m02-ng-top-colleagues/404.html
      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_dist
          path: dist  
  deploy:
    name: Deploy to Pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: deploy_dist
      - name: Deploy to Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          BRANCH: gh-pages
          FOLDER: deploy_dist/2023-09-04_2023_m02-ng-top-colleagues
